name: Deploy to GCS

on:
  push:
    branches:
      - sdx

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        id: build
        env:
          NODE_ENV: development
        run: |
          echo "Creating google application credentials json file"
          echo ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON}}
          echo ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON}} > google-application-credentials.json
          cat google-application-credentials.json
